spring:
#  server:
#    host:
#      api: k8s-cocmtc-cocmtcin-52b788a054-1189666070.ap-northeast-2.elb.amazonaws.com
  datasource:
    url: jdbc:postgresql://15.165.34.151:5432/mtc_db
    username: team9
    password: cocteam9(
    driver-class-name: org.postgresql.Driver

  kafka:
    # group-id 뭘로 넣어야 하지?
    bootstrap-servers: ${KAFKA_NODE1:3.37.4.10:9092},${KAFKA_NODE2:15.165.81.7:9092},${KAFKA_NODE3:54.180.190.136:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: amugurnahasam
      enable-auto-commit: off
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: result.converters.MessageDeserializer